### PR TITLE
Fixes after first milestone

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Fiser33** [comment]
Proc jsi mazal ty @NamedQueries? CrudRepository si je umi vytvorit sam jen podle nazvu parametru?

**Comment by ghost** [comment]
Hej tie named queries boli v tomto pripade zbytocne, funguje to aj takto. Tu je vsetko co si vie odvodit: http://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation v table4

**Review by Fiser33 — DISMISSED** [review]
Ty queries jsou dost dobry teda!

**Comment by ghost** [comment]
Jj je to uplne pecka.

Aj mna to napadlo, ale uz som to nestihal vcera.

**Comment by rudky4** [comment]
@mitko501 Bottle by malo este obsahovat manufacturedBy (vyrobca flase), inak je to super a mozes potom rovno spravit merge.

**Review by rudky4 — APPROVED** [review]
Looking good

**Pull request merged**
